version: '3'
services:
  bot:
    image: sob
    environment:
      - SLACK_BOT_TOKEN=${SLACK_BOT_TOKEN}
      - SLACK_SIGNING_SECRET=${SLACK_SIGNING_SECRET}
      - SLACK_APP_TOKEN=${SLACK_APP_TOKEN}
      - PORT=3000
    build:
      context: sob
      dockerfile: Dockerfile
    ports:
      - ${PORT}:3000
